name: Create Discord Forum Post from Issue

on:
  issues:
    types: [opened]

jobs:
  create-forum-post:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Discord Forum Post
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_FORUM_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          # Prepare issue body - escape special characters and make it JSON-safe
          ISSUE_BODY=$(echo '${{ github.event.issue.body }}' | sed 's/"/\\"/g' | sed 's/\n/\\n/g')
          ISSUE_TITLE=$(echo '${{ github.event.issue.title }}' | sed 's/"/\\"/g')
          
          echo "Creating forum post..."
          FORUM_POST=$(curl -s -X POST \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            "https://discord.com/api/v10/channels/$DISCORD_FORUM_ID/threads" \
            -d "{
              \"name\": \"$ISSUE_TITLE\",
              \"message\": {
                \"content\": \"🔔 New GitHub Issue Created\",
                \"embeds\": [{
                  \"title\": \"$ISSUE_TITLE\",
                  \"url\": \"${{ github.event.issue.html_url }}\",
                  \"description\": \"$ISSUE_BODY\",
                  \"color\": 5814783,
                  \"footer\": {
                    \"text\": \"GitHub Issue #${{ github.event.issue.number }}\"
                  }
                }]
              },
              \"applied_tags\": [],
              \"auto_archive_duration\": 1440
            }")
          
          # Check if forum post was created successfully
          if ! echo "$FORUM_POST" | jq -e '.id' > /dev/null; then
            echo "Failed to create forum post:"
            echo "$FORUM_POST" | jq '.'
            exit 1
          fi
          
          # Get forum post ID
          THREAD_ID=$(echo "$FORUM_POST" | jq -r '.id')
          echo "Forum post created with ID: $THREAD_ID"
          
          # Send additional details as a follow-up message
          echo "Sending additional details..."
          curl -s -X POST \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            "https://discord.com/api/v10/channels/$THREAD_ID/messages" \
            -d "{
              \"content\": \"**Issue Details:**\n• Created by: @${{ github.event.issue.user.login }}\n• Repository: ${{ github.repository }}\n• Link: ${{ github.event.issue.html_url }}\n\nUse this forum post for discussion and updates about this issue.\"
            }"

      - name: Update Issue with Discord Link
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `✨ Discord forum post created in <#${{ env.DISCORD_FORUM_ID }}>`
            });
